<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-11-13T07:51:36Z" name="Yolo API Test Suite" finished-at="2021-11-13T07:51:51Z" duration-ms="14264">
    <groups>
      <group name="yoloAPITest">
        <method signature="PostAndUpdateTestCases.postCreateUser()[pri:0, instance:com.yolo.api.test.suite.invoker.PostAndUpdateTestCases@79b08632]" name="postCreateUser" class="com.yolo.api.test.suite.invoker.PostAndUpdateTestCases"/>
        <method signature="PostAndUpdateTestCases.putUpdateUser()[pri:1, instance:com.yolo.api.test.suite.invoker.PostAndUpdateTestCases@79b08632]" name="putUpdateUser" class="com.yolo.api.test.suite.invoker.PostAndUpdateTestCases"/>
      </group> <!-- yoloAPITest -->
    </groups>
    <test started-at="2021-11-13T07:51:36Z" name="yoloAPITest" finished-at="2021-11-13T07:51:51Z" duration-ms="14264">
      <class name="com.yolo.api.test.suite.invoker.PostAndUpdateTestCases">
        <test-method signature="postCreateUser()[pri:0, instance:com.yolo.api.test.suite.invoker.PostAndUpdateTestCases@79b08632]" started-at="2021-11-13T07:51:36Z" name="postCreateUser" finished-at="2021-11-13T07:51:41Z" duration-ms="4795" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCreateUser -->
        <test-method signature="putUpdateUser()[pri:1, instance:com.yolo.api.test.suite.invoker.PostAndUpdateTestCases@79b08632]" started-at="2021-11-13T07:51:41Z" name="putUpdateUser" finished-at="2021-11-13T07:51:50Z" duration-ms="9387" status="FAIL">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected not same]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected not same
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.failSame(Assert.java:271)
at junit.framework.Assert.assertNotSame(Assert.java:257)
at junit.framework.Assert.assertNotSame(Assert.java:264)
at com.yolo.api.test.suite.invoker.PostAndUpdateTestCases.putUpdateUser(PostAndUpdateTestCases.java:65)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- putUpdateUser -->
      </class> <!-- com.yolo.api.test.suite.invoker.PostAndUpdateTestCases -->
    </test> <!-- yoloAPITest -->
  </suite> <!-- Yolo API Test Suite -->
</testng-results>
